---
# File: password.yml
# Type: task
# Part: MySQL

- name: MySQL | Check for previous installation
  shell: "[ -f /usr/sbin/mysqld ]"
  when: mysql_root_password is defined
  register: mysqld_exists
  ignore_errors: True
- name: MySQL | Preseed MySQL file
  template: src=mysql_seed.j2 dest=/root/mysql.seed
  when: mysqld_exists|failed
- command: /usr/bin/debconf-set-selections /root/mysql.seed
  when: mysqld_exists|failed
